/**
 * Base envelope shared by every domain event.
 *
 * Conventions:
 * - `type` is the stable channel identifier (`<resource>.<pastVerb>`).
 * - `version` is the semver of the event payload contract. Bump on breaking
 *   changes — consumers can opt-in to new versions.
 * - `occurredAt` is the ISO-8601 timestamp generated by the producer.
 * - `data` carries the typed payload.
 */
export interface DomainEvent<TType extends string, TData, TVersion extends string = '1.0.0'> {
  type: TType;
  version: TVersion;
  occurredAt: string;
  /** Optional correlation id for end-to-end tracing. */
  correlationId?: string;
  /** Optional id of the actor that caused the event (User id). */
  actorId?: string;
  data: TData;
}
